---
# This workflow integrates ShiftLeft NG SAST with GitHub
# Visit https://docs.shiftleft.io for help
name: ShiftLeft

on:
  pull_request:
  workflow_dispatch:

jobs:
  NextGen-Static-Analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # We are building this application with Java 11
    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 11.0.x
    - name: Package with maven
      run: mvn compile package
    - name: Download ShiftLeft CLI
      run: |
        curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl
    # ShiftLeft requires Java 1.8. Post the package step override the version
    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: NextGen Static Analysis
      run: ${GITHUB_WORKSPACE}/sl analyze --wait --app Benchmark --tag branch=${{ github.head_ref || steps.extract_branch.outputs.branch }} --java --cpg target/benchmark.war
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
  OWASP-Benchmark-Score:
    runs-on: ubuntu-20.04
    needs: NextGen-Static-Analysis
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 11.0.x
    - name: Export NG SAST Findings
      run: |
        cd $HOME
        git clone --depth 1 --branch v0.0.2  https://github.com/ShiftLeftSecurity/field-integrations
        cd field-integrations/shiftleft-utils || exit 1
        mkdir -p ${GITHUB_WORKSPACE}/ngsast_results
        pip3 install -r requirements.txt
        python3 export.py --app Benchmark -f sl -o ${GITHUB_WORKSPACE}/ngsast_results/Benchmark.sl
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
    - name: Package with maven
      run: mvn compile package
    - name: Calculate OWASP Benchmark Score
      run: |
        cd ${GITHUB_WORKSPACE}
        mvn validate -Pbenchmarkscore -Dexec.args="expectedresults-1.2.csv ngsast_results ShiftLeft anonymous"
        if [ -e "scorecard/Benchmark_Scorecard_for_ShiftLeft.html" ]; then
            echo "*** Thank you for Benchmarking ShiftLeft NextGen Static Analysis ***"
            echo "You can find the results for ShiftLeft under workflow artifacts called scorecard"
        else
            echo "Benchmark results were not produced correctly. Check if you have Java 1.8 installed"
        fi
    - uses: actions/upload-artifact@v2
      with:
        name: scorecard
        path: scorecard
